
name: run-pyscan
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-pyscan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: login to github packages
        run: docker login -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}} docker.pkg.github.com
      - name: get curr
        run: echo "/path/to/dir" >> $GITHUB_PATH
      - name: pull pyscan image
        run: docker pull docker.pkg.github.com/raiyanyahya/pyscan/pyscan:latest
      - name: run image
        run: docker run -v ${PWD}:/workdir:delegated docker.pkg.github.com/raiyanyahya/pyscan/pyscan